# Generated by Django 5.1.1 on 2024-10-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0004_remove_secuenciamovimiento_privado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotDatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("ip", models.GenericIPAddressField(protocol="IPv4", unique=True)),
                ("minH", models.DecimalField(decimal_places=4, max_digits=5)),
                ("minmaxJoints", models.JSONField()),
            ],
        ),
    ]
